title:
  archive: 归档
  category: 分类
  tag: 标签
  schedule: 日程表

author: Ignorance

menu:
  home: Home
  archives: Archives
  categories: Categories
  tags: Tags
  about: About
  search: Search
  schedule: Schedule
  sitemap: Sitemap
  commonweal: Commonweal 404

sidebar:
  overview: 站点概要
  toc: 文章目录

post:
  created: Post created
  modified: Post modified
  sticky: Sticky
  posted: Posted on
  in: In
  more: more
  read_more: Read more
  untitled: Untitled
  toc_empty: This post does not have a Table of Contents
  visitors: 热度
  wordcount: Words count in article
  min2read: Reading time
  totalcount: Site words total count
  copyright:
    author: Post author
    link: Post link
    license_title: Copyright Notice
    license_content: 'All articles should not be used in other businesses. All rights reserved by the author.'

page:
  totally: Totally
  tags: tags

footer:
  powered: 备案/许可证编号为：晋ICP备18012867号"
  theme: 博客

counter:
  tag_cloud:
    zero: No tags
    one: 1 tag in total
    other: "%d tags in total"

  categories:
    zero: No categories
    one: 1 category in total
    other: "%d categories in total"

  archive_posts:
    zero: No posts.
    one: 1 post.
    other: "%d posts in total."

state:
  posts: posts
  pages: pages
  tags: tags
  categories: categories

search:
  placeholder: Searching...

cheers:
  um: Um..
  ok: OK
  nice: Nice
  good: Good
  great: Great
  excellent: Excellent

keep_on: Keep on posting.

symbol:
  comma: ', '
  period: '. '
  colon: ':'

reward:
  donate: Donate
  wechatpay: WeChat Pay
  alipay: Alipay
  bitcoin: Bitcoin
